### ISSUE TITLE
[tests] timezone

### ISSUE THREAD

**Issue by fernandomg** [monerium/js-sdk#70]
While working on #69, running the tests for the SDK I stumbled upon a restriction in the dates being used:

Everything works fine while the app running the tests is in GMT, but if it happens like in my case that I'm in GMT+1, everything related to dates fails.

First, the matching regex for checking the "send message", should check for [`Z` or `+/-nn:nn`](https://regexper.com/#%5Cd%7B4%7D-%5Cd%7B2%7D-%5Cd%7B2%7DT%5Cd%7B2%7D%3A%5Cd%7B2%7D%3A%5Cd%7B2%7D%28Z%7C%5B-%2B%5D%5Cd%7B2%7D%3A%5Cd%7B2%7D%29%24), so the resulting regex should be rewritten to: `/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(Z|[-+]\d{2}:\d{2})$/`

On the other hand, the tests for `rfc3339`, have an assertion to a hardcoded string that assumes GMT.

Doing a bit of research, I found what can be a solution (this requires adding a dependency): https://stackoverflow.com/a/77603606

The latter will allow you to tweak the TZ on demand, which will help to make the `rfc3339` tests pass without trouble. Allowing as well the possibility to evaluate different "send message" strings depending on a variety of TZs.

**Comment by einaralex** [comment]
Thank you so much!
