### ISSUE TITLE
Supporting Document upload rejected by CORS

### ISSUE THREAD

**Issue by fernandomg** [monerium/js-sdk#83]
**Describe the bug**
hello, I'm trying to use the SDK's uploadSupportingDocument method, but I'm getting a CORS error and can't upload the corresponding file.

Is there anything I have to do to make it work?

Is it related to the 'Redirect URI' set in the monerium app?

**Comment by einaralex** [comment]
This works now in version 2.12.0, it was pointing to a deprecated endpoint.
