### ISSUE TITLE
Some transactions are missing from the transaction history

### ISSUE THREAD

**Issue by kevtechi** [monerium/js-sdk#86]
**Describe the bug**
Not all EURe transactions show in the transaction history for a given account even though the balance is updated.

This makes the download CSV feature unreliable.

Compare our EURe transaction list to what is actually available on the dashboard: https://polygonscan.com/token/0x18ec0a6e18e5bc3784fdd3a3634b31245ab704f6?a=0xf5D0181b80E1C793D98b95BFF0E6CDe1D27a3ef8 

These transactions are not visible in our history: 
- https://polygonscan.com/tx/0x794f030f598f93034cfc1ddd1634c3d4297f6ffe40f2892fbf9f7541b34a063e 
- https://polygonscan.com/tx/0xc46eae0669898300309acbdf5d91b03f48b8d7eb71011d5e964f778f9f8d4bde
- https://polygonscan.com/tx/0x462fc71525f02a563916e850c8b64c0f056766c4fc49d39c07d5ae31875ad5a0
- and a few others.

**To Reproduce**

We swapped USDC for EURe which triggers a "transfer" event as normal on chain but no data in transaction history. 

We also simply made a transfer directly from our EOA out to another account.

**Expected behavior**
I expect my transaction history for a connected EURe account to match the on-chain transaction history for a EURe account.

**Desktop (please complete the following information):**

Not browser related.

**Smartphone (please complete the following information):**

Not device related.

**Additional context**

It would seem like only transactions triggered through the interface or incoming to the IBAN get reflected in the transaction history.

**Comment by einaralex** [comment]
Currently, our internal system does not track tx's made outside of interacting with the API.
It's something we'd like to do in the future, but not on the drawing board.
